#!/bin/bash

## Compress the git repo into a .zip

git -C . rev-parse 2>/dev/null
is_git_path=$(echo $?)

if [[ "$is_git_path" -ne 0 ]]; then
	echo "This script must be executed from within a git repo."
	exit 1
fi

dirname=${PWD##*/}
git archive --prefix "${dirname}"/ HEAD -o "../${dirname}".zip

## Delete ignored files (node modules, angular cache, ...)

set -euo pipefail
IFS=$'\n\t'

ignored=$(git status --ignored --porcelain)

for i in $ignored; do
	path=${i:3}
	echo "Deleting $path..."
	rm -rf $path
done
